export const NEW_TRANSACTION = '💸 New transaction'
export const NEW_BALANCE = '📊 New balance'
export const NEW_NOTE = '🗒 New note'
export const CANCEL = '🚫 Cancel'
export const DONE = '✅ Done'
export const CONFIRM = '✅ Confirm'
export const GET_ERRORS = '🐛 Errors'
export const USE_SHORTCUT = '💨 Shortcuts'
